version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: apnedoctors-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    volumes:
      - ./data/chroma_db:/app/data/chroma_db
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - apnedoctors-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: apnedoctors-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_ENVIRONMENT=production
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - apnedoctors-network

networks:
  apnedoctors-network:
    driver: bridge
    name: apnedoctors-network
